apiVersion: v1
kind: Pod
metadata:
  labels:
    run: http-pod
  name: http-pod
spec:
  containers:
  - image: nginx 
    name: http-pod
    ports:
    - containerPort: 80
      name: http-port
    livenessProbe:
      httpGet:
        path: /
        port: http-port
      periodSeconds: 5
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
