apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: self-healing
  name: self-healing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-healing
  strategy: {}
  template:
    metadata:
      labels:
        app: self-healing
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
