apiVersion: v1
kind: LimitRange
metadata:
  name: request-constraint
  namespace: dev
spec:
  limits:
  - defaultRequest: # this section defines default requests
      cpu: 100m
      memory: 128Mi
    type: Container