apiVersion: v1
kind: Pod
metadata:
  name: log-processor
spec:
  containers:
    - name: writer
      image: busybox:latest
      command: ["sh", "-c", "while true; do echo \"$(date)\" >> /data/logs.txt; sleep 5; done;"]
      volumeMounts:
        - name: shared-path
          mountPath: /data
    - name: reader
      image: busybox:latest
      command: ["sh", "-c"]
      args:
        - -c
        - |
          while true; do
            if [ -f /data/logs.txt ]; then
              tail -n 10 /data/logs.txt;
            else
              echo "not found";
            fi
            sleep 10;
          done;
      volumeMounts:
        - name: shared-path
          mountPath: /data
  volumes:
    - name: shared-path
      emptyDir: {}
       
