apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: critical-app
  name: critical-app
  namespace: dev-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: critical-app
  strategy: {}
  template:
    metadata:
      labels:
        app: critical-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: 
          requests:
            cpu: 1
            memory: 1Gi
      priorityClassName: high-priority
status: {}
