apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-delete-2gi
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data
