apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retain-1gi
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
