apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: stateful-pod
  serviceName: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: stateful-pod
    spec:
      containers:
        - name: stateful-pod
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10

