apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: app-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: blue 
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
        version: blue 
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
        resources: {}
status: {}
