apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: app-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: green
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
        resources: {}
status: {}
