apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-role
  namespace: staging
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - update
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]


