apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-dep
  name: svc-port
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  - port: 443
    protocol: TCP
    targetPort: https
    name: https
  selector:
    app: test-dep
  type: ClusterIP
status:
  loadBalancer: {}
