apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
    version: v1
  name: api-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
