apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-secret-as-env
  name: pod-with-secret-as-env
spec:
  containers:
  - image: busybox
    name: pod-with-secret-as-env
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
