apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-worker
spec:
  jobTemplate:
    metadata:
      name: batch-worker
    spec:
      parallelism: 3
      completions: 9
      template:
        metadata: {}
        spec:
          containers:
          - image: busybox
            name: batch-worker
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 */1 * * *
status: {}
