apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app-logger
  name: app-logger
spec:
  containers:
  - image: nginx:alpine
    name: web
    command: 
      - /bin/sh
      - -c
      - nginx -g 'daemon off;'
    volumeMounts:
      - name: logs
        mountPath: /var/log/nginx 
  - image: busybox:latest 
    name: log-shipper 
    command: ['sh', '-c', 'while true; do tail -f /logs/access.log || sleep 5; done']
    volumeMounts:
      - name: logs
        mountPath: /logs
  volumes:
    - name: logs
      emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
