apiVersion: v1
kind: Pod
metadata:
  labels:
    run: probe-failure
  name: probe-failure
spec:
  containers:
  - image: nginx
    name: probe-failure
    ports:
    - containerPort: 80
      name: http
    livenessProbe:
      httpGet:
        port: http
        path: /live
      periodSeconds: 10
      failureThreshold: 10
    readinessProbe:
      httpGet:
        port: http
        path: /ready
      periodSeconds: 5
      failureThreshold: 10
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
