apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-host
spec:
  rules:
  - host: app1.example.com
    http:
      paths:
      - backend:
          service:
            name: app1-svc
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: app2.example.com
    http:
      paths:
      - backend:
          service:
            name: app2-svc
            port:
              number: 9090
        path: /
        pathType: Prefix
