apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
    - name: test
      image: busybox:1.36.1
      restartPolicy: Never
      command: ["sleep","3600"]
