## nginx cannot run as non root so this container will fail
apiVersion: v1
kind: Pod
metadata:
    name: non-root
spec:
  containers:
  - image: nginx:1.18.0
    name: secured-container
    securityContext:
      runAsNonRoot: true
