apiVersion: v1
kind: Pod
metadata:
  name: fs-secured
  namespace: ckad2
spec:
  securityContext:
    fsGroup: 3000
  containers:
  - image: nginx:1.18.0
    name: secured-container
    volumeMounts:
    - name: data-volume
      mountPath: /data/app
  volumes:
  - name: data-volume
    emptyDir: {}
