apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selector
  name: selector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      version: v2
  strategy: {}
  template:
    metadata:
      labels:
        app: api
        version: v2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
