apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  strategy: {}
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        resources: {}
status: {}
