apiVersion: v1
kind: Service
metadata:
  labels:
    app: multi-port-svc
  name: multi-port-svc
spec:
  ports:
  - name: http 
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https 
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: api 
  type: ClusterIP
status:
  loadBalancer: {}
