apiVersion: v1
kind: Pod
metadata:
  labels:
    run: delayed-start
  name: delayed-start
spec:
  initContainers:
  - image: busybox
    name: delayed-start
    command: ["sh", "-c", "sleep 60"]
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
      name: http
    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 15
      failureThreshold: 5 
    livenessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
      failureThreshold: 12      
