apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: legacy-endpoint
  labels:
    kubernetes.io/service-name: legacy-app
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8080
endpoints:
  - addresses:
      - "10.0.0.5"
