apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rate-limited
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  rules:
  - host: api.example.com
    http:
      paths:
      - backend:
          service:
            name: api-svc
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
