apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: v.1.2.4
    env: prod
    team: legacy
  name: backend
spec:
  containers:
  - image: nginx:1.25.1
    name: backend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
