apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
    team: shiny
  name: frontend
spec:
  containers:
  - image: nginx:1.25.1
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
