apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: progressive
  name: progressive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: progressive
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 120
  template:
    metadata:
      labels:
        app: progressive
    spec:
      containers:
      - image: nginx
        name: nginx
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        resources: {}
status: {}
