apiVersion: v1
kind: Pod
metadata:
  labels:
    run: data-pod
  name: data-pod
spec:
  volumes:
  - name: pvc
    persistentVolumeClaim: 
      claimName: app-pvc 
  containers:
  - image: nginx
    name: data-pod
    volumeMounts:
    - mountPath: /data
      name: pvc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
