apiVersion: v1
kind: Pod
metadata:
  labels:
    run: combined
  name: combined
spec:
  containers:
  - image: nginx
    name: combined
    ports:
    - containerPort: 80
    lifecycle:
      postStart:
        exec:
          command: 
          - sh
          - -c
          - touch /tmp/logs.txt && echo $(date) >> /tmp/logs.txt
    readinessProbe: 
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 10
      failureThreshold: 5
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/logs.txt
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 10
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
