apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-container
  name: multi-container
spec:
  containers:
  - image: nginx
    name: web 
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 10
      failureThreshold: 1
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 5
  - image: busybox
    name: sidecar
    command: ["sh", "-c", "touch /tmp/healthy && sleep 3600"]
    livenessProbe:
      exec:
        command: ["cat","/tmp/healthy"]
    readinessProbe:
      exec:
        command: ["cat","/tmp/healthy"] 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
