apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache
  strategy: {}
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - image: redis:6
        name: redis
        resources: {}
status: {}
