apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-nodeport
  name: web-nodeport
spec:
  ports:
  - name: 80-8080
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-app
  type: NodePort
status:
  loadBalancer: {}
