apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-app
  name: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  strategy: {}
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        resources: {}
status: {}
