apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: security-context-demo
  name: security-context-demo
spec:
  containers:
  - image: alpine
    name: security-context-demo
    resources: {}
    securityContext:
      capabilities:
        add: ["SYS_TIME","SYS_ADMIN"]
  dnsPolicy: ClusterFirst
status: {}
