apiVersion: v1
kind: Pod
metadata:
  labels:
    run: success-threshold
  name: success-threshold
spec:
  containers:
  - image: nginx
    name: success-threshold
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 5
      successThreshold: 3
      failureThreshold: 10
