apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - image: nginx:latest
      name: web-server
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "0.1"
          memory: "128Mi"
        limits:
          cpu: "0.5"
          memory: "256Mi"

