apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-generator
spec:
  concurrencyPolicy: Forbid 
  jobTemplate:
    metadata:
      name: report-generator
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - image: busybox
            name: report-generator
            command: ["sh", "-c", "echo 'Generating report'"]
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/15 * * * *'
status: {}
