apiVersion: v1
kind: Pod
metadata:
  name: data-exchange
spec:
  containers:
    - name: main-app
      image: busybox
      command: ['sh', '-c', 'counter=1; while true; do touch "/var/app/data/$counter-data.txt"; counter=$((counter+1)); sleep 30; done']
      volumeMounts:
        - name: data-volume
          mountPath: /var/app/data
    - name: sidecar
      image: busybox
      command: ['sh', '-c', 'while true; do ls -d /var/app/data/*-data.txt | wc -l; sleep 30; done']
      volumeMounts:
        - name: data-volume
          mountPath: /var/app/data
  volumes:
    - name: data-volume
      emptyDir: {}
