apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary-new
  name: canary-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
  strategy: {}
  template:
    metadata:
      labels:
        app: canary
        version: new
    spec:
      containers:
      - image: nginx:1.24
        name: nginx
        resources: {}
status: {}
