apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-access
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
#          matchExpressions:
#            - key: namespace
#              operator: In
#              values: ["app-namespace"]
          matchLabels:
            name: app-namespace
      ports:
        - port: 3306
            


