apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    tier: frontend
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            memory: 64Mi
            cpu: 100m
status: {}
