apiVersion: v1
kind: Pod
metadata:
  name: configured-pod
  namespace: ckad2
spec:
  containers:
  - name: app
    image: nginx:1.19.0
    volumeMounts:
    - name: secret-volume
      mountPath: /var/app
      readOnly: true
  volumes:
  - name: secret-volume
    secret: 
      secretName: ssh-key

