apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-app
  name: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        resources: {}
status: {}
