apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pv-pod
  name: pv-pod
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: app-pvc
  containers:
  - image: busybox
    name: pv-pod
    command: ["sh", "-c", "touch /data/test.txt && sleep 3600"]
    volumeMounts:
      - mountPath: "/data"
        name: storage
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
