apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: web-policy
spec:
  podSelector:
    matchLabels:
      tier: web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: 80
        - port: 443

