apiVersion: v1
kind: Pod
metadata:
  labels:
    run: timeout-pod
  name: timeout-pod
spec:
  containers:
  - image: nginx
    name: timeout-pod
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      timeoutSeconds: 3
      periodSeconds: 10
      failureThreshold: 3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
