apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: health-app
  name: health-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-app
  strategy: {}
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
status: {}
