apiVersion: v1
kind: Pod
metadata:
  name: shared-vol-pod
spec:
  volumes:
    - name: shared-vol
      emptyDir: {}
  initContainers:
    - name: init
      image: busybox
      command: ["sh","-c","touch /data/log.txt && echo $(date) >> /data/log.txt"]
      volumeMounts:
        - name: shared-vol
          mountPath: /data
  containers:
    - name: read
      image: busybox
      command: 
        - sh
        - -c
        - |
          cat /data/log.txt
          sleep 3600
      volumeMounts:
        - name: shared-vol
          mountPath: /data
