apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: ckad2
spec:
  hard:
    pods: 2
    requests.cpu: "1"
    requests.memory: 1024m
    limits.cpu: "2"
    limits.memory: 2048m
