apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-labels
  name: svc-labels
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
    env: production
  type: ClusterIP
status:
  loadBalancer: {}
