apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
    - image: bmuschko/nodejs-hello-world:1.0.0
      name: hello-world
      ports:
        - name: nodejs-port
          containerPort: 3000
      readinessProbe:
        httpGet:
          path: /
          port: nodejs-port
        initialDelaySeconds: 2
        periodSeconds: 8  
