apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-pod
  name: redis-pod
spec:
  volumes:
  - name: redis-configmap
    configMap:
      name: redis-config
  - name: redis-config
    emptyDir: {}
  - name: redis-data
    emptyDir: {}
  initContainers:
  - image: busybox
    name: init-redis
    command:
     - sh
     - -c
     - touch /redis-master/redis.conf
     - cat maxmemory $(cat /configmap/maxmemory) >> /redis-master/redis.conf
     - cat maxmemory-policy $(cat /configmap/maxmemory-policy) >> /redis-master/redis.conf
    volumeMounts:
    - name: redis-configmap
      mountPath: /configmap
    - name: redis-config
      mountPath: /redis-master
  containers:
  - image: redis:7
    name: redis-pod
    ports:
    - containerPort: 6379
    command:
    - redis-server
    - /redis-master/redis.conf
    volumeMounts:
    - name: redis-config
      mountPath: /redis-master
