apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  volumes:
    - name: workdir
      emptyDir: {}
  initContainers:
    - name: setup
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: 
        - "echo 'Setup Complete' > /work-dir/initialized.txt"
      volumeMounts:
        - name: workdir
          mountPath: /work-dir
  containers:
    - image: nginx:latest
      name: web
      resources: {}
      volumeMounts: 
        - name: workdir
          mountPath: /usr/share/nginx/html
