apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-backup
spec:
  jobTemplate:
    metadata:
      name: hourly-backup
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - image: busybox
            name: hourly-backup
            command: ["sh", "-c", "echo backup started at $(date)"]
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 */1 * * *
status: {}
