apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resource-app
  name: resource-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-app
  strategy: {}
  template:
    metadata:
      labels:
        app: resource-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi  
status: {}
