apiVersion: v1
data:
  token: WVdKak1USXplSGw2Q2c9PQ==
  username: WVhCcGRYTmxjZ289
kind: Secret
metadata:
  creationTimestamp: "2025-11-26T05:25:29Z"
  name: api-credentials
  namespace: default
  resourceVersion: "18087"
  uid: 32e9f132-d0a9-4ed2-b422-1f04e824726b
type: Opaque
