apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secure-app
  name: secure-app
spec:
  serviceAccountName: app-sa
  containers:
  - image: nginx:1.20
    name: secure-app
    resources: {}
    env:
      - name: USER_NAME
        valueFrom:
          secretKeyRef:
            name: api-credentials
            key: username
      - name: TOKEN
        valueFrom:
          secretKeyRef:
            name: api-credentials
            key: token
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
