apiVersion: v1
kind: Service
metadata:
  labels:
    app: echoserver
  name: echoserver
  namespace: default
spec:
  clusterIP: 10.110.255.62
  clusterIPs:
  - 10.110.255.62
  ports:
  - name: 5005-8080
    nodePort: 32069
    port: 5005
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver
  type: NodePort
