apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /api/health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 1
      failureThreshold: 1
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - curl -f http://database:5432/health
      initialDelaySeconds: 5
      periodSeconds: 5
    startupProbe:
      httpGet:
        path: /api/startup
        port: 8080
      periodSeconds: 2
      failureThreshold: 5
