apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-svc
  name: backend-svc
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}
