apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
      - containerPort: 80
        name: nginx-port
      startupProbe:
        httpGet:
          path: /
          port: nginx-port
      readinessProbe:
        httpGet:
          path: /
          port: nginx-port
        initialDelaySeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: nginx-port
        initialDelaySeconds: 10
        periodSeconds: 30
