apiVersion: v1
kind: Pod
metadata:
  labels:
    run: slow-start
  name: slow-start
spec:
  containers:
  - image: nginx
    name: slow-start
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 0
      failureThreshold: 30
      periodSeconds: 10
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
