# created imperatively with following command
# k create service loadbalancer echoserver --tcp=5005:8080
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  clusterIP: 10.103.110.145
  clusterIPs:
  - 10.103.110.145
  ipFamilies:
  ports:
  - name: 5005-8080
    nodePort: 30751
    port: 5005
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver
  type: LoadBalancer
