apiVersion: v1
kind: Deployment
metadata:
  name: web-serer
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 40%
      maxSurge: 10%
  minReadySeconds: 60
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      lables:
        app: httpd
  spec:
    containers:
      - name: httpd
        image: httpd:2.4.23-alpine
        ports:
         - containerPort: 80
           protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
