apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-server
  name: app-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-server
  strategy: {}
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - image: nginx:1.24
        name: nginx
        resources: {}
status: {}
