apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-access
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
    - Ingress
  ingress:
    - from: 
      - ipBlock:
          cidr: 192.168.1.0/24
          except:
            - 192.168.1.5/32
      ports:
        - port: 80
