apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-deploy-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-manager
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: default
