apiVersion: v1
kind: Service
metadata:
  labels:
    app: headless-service
  name: headless-service
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
  clusterIP: None
  selector:
    app: headless-service
