apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-ephemeral-vol
  name: pod-ephemeral-vol
spec:
  volumes:
    - name: temp-vol
      emptyDir:
        sizeLimit: 256Mi
        medium: Memory
  containers:
  - image: busybox
    name: pod-ephemeral-vol
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
      - name: temp-vol
        mountPath: /tmp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
