apiVersion: batch/v1
kind: Job
metadata:
  name: timed-task
spec:
  activeDeadlineSeconds: 30
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - sleep
        - "60"
        image: busybox
        name: timed-task
        resources: {}
      restartPolicy: Never
status: {}
