apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-svc
  namespace: backend
spec:
  ports:
  - name: "8080"
    nodePort: 32567
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-svc
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
