apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dns-test
  name: dns-test
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: dns-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
