apiVersion: v1
kind: Service
metadata:
  labels:
    app: testpods
  name: old-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: testpods
  type: LoadBalancer
status:
  loadBalancer: {}
