apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: pod1
spec:
  volumes:
    - name: rwo
      persistentVolumeClaim:
        claimName: rwo-pvc
  containers:
  - image: nginx
    name: pod1
    resources: {}
    volumeMounts:
    - name: rwo
      mountPath: /data
      subPath: logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
