apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekly-report
spec:
  jobTemplate:
    metadata:
      name: weekly-report
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - image: busybox
            name: weekly-report
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 0 * * 0
status: {}
