apiVersion: v1
kind: Pod
metadata:
  name: multi-app
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  initContainers:
    - name: volume-check
      image: busybox:1.36.1
      command: ['sh', '-c', 'echo "Checking if volume is mounted" && ls /shared-data && touch /shared-data/testfile']
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-data
  containers:
    - name: app
      image: nginx:1.21
      ports:
        - containerPort: 80
    - name: sidecar
      image: busybox:latest
      command: ['sh', '-c', 'while true; do sleep 3600; done']
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-data
    
