apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rolling-app
  name: rolling-app
spec:
  replicas: 6 
  selector:
    matchLabels:
      app: rolling-app
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: rolling-app
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        resources: {}
status: {}
