apiVersion: v1
kind: Service
metadata:
  labels:
    app: sticky-svc
  name: sticky-svc
spec:
  sessionAffinity: ClientIP
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: session-app 
  type: ClusterIP
status:
  loadBalancer: {}
