apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: critical-app
  name: critical-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: critical-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: critical-app
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5 
        resources: {}
status: {}
