apiVersion: batch/v1
kind: Job
metadata:
  name: batch-process
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
        - name: batch-process
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - 'echo "Processing data..." && sleep 10 && echo "Done"'
      restartPolicy: Never
  backoffLimit: 3
