apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-headless
  name: mysql-headless
spec:
  clusterIP: None
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
  selector:
    app: mysql 
