apiVersion: v1
kind: LimitRange
metadata:
  name: lr
  namespace: limited-ns
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 100m
        memory: 128Mi
      type: Container
