apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: limited-ns
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    pods: "50"
    

