apiVersion: v1
kind: Pod
metadata:
  name: test-pod-valid
  namespace: limited-ns
spec:
  containers:
  - image: nginx:latest
    name: test-pod-valid
    resources:
      limits:
        cpu: 150m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
