apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: app
      image: alpine:3.18.2
      command: ["sh","-c","while true; do sleep 60; done;"]
      volumeMounts:
        - mountPath: "/data"
          name: app-storage
