apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: temporary
  name: temporary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temporary
  strategy: {}
  template:
    metadata:
      labels:
        app: temporary
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 3 
        resources: {}
status: {}
