apiVersion: v1
kind: Pod
metadata:
  labels:
    run: custom-headers
  name: custom-headers
spec:
  containers:
  - image: nginx
    name: custom-headers
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
        httpHeaders:
          - name: X-custom-header
            value: Awesome
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
