apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
  name: blue-green
spec:
  ports:
  - name: http 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: green 
  type: ClusterIP
status:
  loadBalancer: {}
