apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green
  name: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  strategy: {}
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: nginx:1.24
        name: nginx
        resources: {}
status: {}
